version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}        
  cache:
    image: redis
    ports:
      - 6379:6379    
  takaro:
    build:
      context: .
      dockerfile: containers/generic-app.Dockerfile.dev
#      args:
#       NODE_ENV: development
#    command: "npm run start:dev"
    volumes:
      - ./packages:/app/packages
    ports:
      - 13000:3000
      - 12001:12000

