version: '3.1'
services :
  postgresql:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./_data/db:/var/lib/postgresql      
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}        
#  cache:
#    image: redis
#    ports:
#      - 6379:6379    
  takaro:
    build:
      context: .
      dockerfile: containers/dev.Dockerfile
#      args:
#       NODE_ENV: development
#    command: "npm run start:dev"
    volumes:
      - ./packages:/app/packages
      - ./prisma:/app/prisma
      - ./_data:/app/_data
    environment:
      LOGGING_LEVEL: debug
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}"
    ports:
    # api
      - 13000:3000
      - 12001:12000
    # web-main
      - 13001:13001
    # lib-components
      - 13002:13002
    # lib-db prisma studio
      - 13003:13003