version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: takaro
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: apidb

  core:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGE: core
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:3000

  cache:
    image: redis
    ports:
      - 6379:6379 
