version: '3.1'
services:
  postgresql:
    extends:
      file: docker-compose.yml
      service: postgresql   

  redis:
    extends:
      file: docker-compose.yml
      service: redis      
  kratos:
    extends:
      file: docker-compose.yml
      service: kratos
  kratos-migrate:
    extends:
      file: docker-compose.yml
      service: kratos-migrate      
  postgresql_kratos:
    extends:
      file: docker-compose.yml
      service: postgresql_kratos      
  hydra:
    extends:
      file: docker-compose.yml
      service: hydra
  hydra-migrate:
    extends:
      file: docker-compose.yml
      service: hydra-migrate   
  postgresql_hydra:
    extends:
      file: docker-compose.yml
      service: postgresql_hydra             
  takaro:
    build:
      context: .
      dockerfile: containers/dev.Dockerfile

    volumes:
      - ./reports:/app/reports      
    environment:
      LOGGING_LEVEL: debug
      #LOGGING_MINIMAL: "true"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}"
      REDIS_HOST: "redis"
      ADMIN_SECRET: "${ADMIN_SECRET}"
      JWT_SECRET: "${JWT_SECRET}"
      FUNCTIONS_EXECUTION_MODE: "local"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}  
      POSTGRES_HOST: "postgresql"   
      POSTGRES_ENCRYPTION_KEY: "${POSTGRES_ENCRYPTION_KEY}"
      ADMIN_CLIENT_ID: ${ADMIN_CLIENT_ID}
      ADMIN_CLIENT_SECRET: ${ADMIN_CLIENT_SECRET}

      REACT_APP_API: http://127.0.0.1:13000
      REACT_APP_ORY_URL: http://127.0.0.1:4433

      TAKARO_OAUTH_HOST: http://hydra:4444
      TAKARO_HOST: http://takaro:3000

    ports:
    # api
      - 13000:3000
      - 12001:12001
    # web-main
      - 13001:13001
    # lib-components storybook
      - 13002:13002
    # agent  
      - 13004:3001
volumes:
    pgadmin:      