name: Node.js CI

on: [pull_request]

jobs:
  node-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        postgres-version: [14]
        redis-version: [6]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: ./scripts/dev-init.sh
      - run: npm run test:style
      - run: mkdir -p reports/mocha
      - run: node scripts/integration-tests.mjs
        env:
          POSTGRES_USER: takaro-user
          POSTGRES_PASSWORD: takaro-pw
          POSTGRES_DB: takaro-db
      - run: ls -la reports
        if: always() # always run even if the previous step fails
      - run: ls -la reports/mocha
        if: always() # always run even if the previous step fails
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: "./reports/mocha/*.xml"
