name: Node.js CI

on: [pull_request]

jobs:
  node-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        postgres-version: [14]
        redis-version: [6]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: ./scripts/dev-init.sh
      - run: npm run test:style
      - run: npm -w packages/test run integration-tests
        env:
          POSTGRES_USER: takaro-user
          POSTGRES_PASSWORD: takaro-pw
          POSTGRES_DB: takaro-db
          TEST_HTTP_TARGET: http://127.0.0.1:13000
