name: Node.js CI

on: [pull_request]

jobs:
  node-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        postgres-version: [14]
        redis-version: [6]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: ./scripts/dev-init.sh
      - run: npm run test:style
      - run: npm run build
      - run: node scripts/integration-tests.mjs
